### ISSUE TITLE
ModuleNotFoundError: No module named 'tools'

### ISSUE THREAD

**Issue by iiegn** [ellepannitto/conll2ske#9]
https://github.com/ellepannitto/conll2ske/blame/b688ee3eb20938844a5b33ddb3e2262d40760041/src/conll2ske/main.py#L8
```bash
$ conll2ske
Traceback (most recent call last):
  File "/home/egon/.pyenv/versions/conll2ske-3.12/bin/conll2ske", line 5, in <module>
    from conll2ske.main import main
  File "/home/egon/Documents/work/eurac/src/conll2ske/src/conll2ske/main.py", line 8, in <module>
    import tools.validate as tools
ModuleNotFoundError: No module named 'tools'
```
...i think, there are some files that need to be `git add`-ed, `commit`-ed and `push`-ed ;)

**Comment by ellepannitto** [comment]
fixed!
